### ISSUE TITLE
Missing _RegisterType R_EIP enum?

### ISSUE THREAD

**Issue by PatrickvL** [gdabah/distorm#110] opened 2017-01-26 15:07 UTC
As the title says, where's the R_EIP enum in _RegisterType?
Should one use R_RIP instead, also on 32 bit decodes?
Or is it an ommision that could be corrected?

**Comment by gdabah** [comment] 2017-01-26 23:07
What use do you have for it in 32 bit? That register doesn't exist.

**Comment by PatrickvL** [comment] 2017-01-27 16:20
Well, in winnt.h, there's an Eip member in the CONTEXT struct (which in turn is pointed to from an LPEXCEPTION_POINTERS member called ContextRecord).

For most other members in the CONTEXT struct, there's a _RegisterType companion, but not Eip - hence tis question.

**Comment by PatrickvL** [comment] 2017-01-27 16:23
Here the code where I was planning to add R_EIP to : https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/master/src/CxbxKrnl/EmuX86.cpp#L260 - it's an exception handler for opcodes that trigger an access violation, when accessing hardware that isn't present, and will have to be emulated in that project.

**Comment by gdabah** [comment] 2017-02-17 16:15
It seems you lack the understanding of how it all works. If you need further help talk to me on distorm@gmail.com, this is not a bug and I'm closing it.

**Closed by gdabah** 2017-02-17 16:15 UTC
